In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"np_array : {np_array}\n, x_np : {x_np}")

np_array : [[1 2]
 [3 4]]
, x_np : tensor([[1, 2],
        [3, 4]])


In [7]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씁니다., [0,1) 의 unifrom 분포
print(f"Random Tensor : \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.9998, 0.5771],
        [0.4775, 0.0566]]) 



In [8]:
shape = (2, 3, )
rand_tensor = torch.rand(shape) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1).
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f" Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor : 
 tensor([[0.0250, 0.9693, 0.0582],
        [0.5018, 0.3573, 0.6139]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

 Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [9]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


In [10]:
# GPU가 존재한다면 텐서를 이동합니다.
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [11]:
tensor.device

device(type='cpu')

In [17]:
tensor = torch.rand(4, 4)
print(tensor)
print(f"First row : {tensor[0]}")
print(f"First column : {tensor[:, 0]}")
print(f"Last column : {tensor[..., -1]}")
print(f"Last column : {tensor[:, -1]}")
tensor[:, 1] = 0
print(tensor)

tensor([[0.5219, 0.6807, 0.9139, 0.1432],
        [0.3364, 0.8627, 0.7071, 0.9078],
        [0.0754, 0.6041, 0.3594, 0.2153],
        [0.1818, 0.3107, 0.6951, 0.8460]])
First row : tensor([0.5219, 0.6807, 0.9139, 0.1432])
First column : tensor([0.5219, 0.3364, 0.0754, 0.1818])
Last column : tensor([0.1432, 0.9078, 0.2153, 0.8460])
Last column : tensor([0.1432, 0.9078, 0.2153, 0.8460])
tensor([[0.5219, 0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460]])


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[0.5219, 0.0000, 0.9139, 0.1432, 0.5219, 0.0000, 0.9139, 0.1432, 0.5219,
         0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078, 0.3364, 0.0000, 0.7071, 0.9078, 0.3364,
         0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153, 0.0754, 0.0000, 0.3594, 0.2153, 0.0754,
         0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460, 0.1818, 0.0000, 0.6951, 0.8460, 0.1818,
         0.0000, 0.6951, 0.8460]])


In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t1)

tensor([[0.5219, 0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460],
        [0.5219, 0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460],
        [0.5219, 0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460]])


In [20]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 같습니다.
y1 = tensor @tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱(element-wise product)를 계산합니다. z1, z2, z3는 모두 같은 값을 같습니다.
z1 = tensor*tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.2723, 0.0000, 0.8352, 0.0205],
        [0.1132, 0.0000, 0.5000, 0.8240],
        [0.0057, 0.0000, 0.1291, 0.0464],
        [0.0331, 0.0000, 0.4831, 0.7157]])

In [21]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.903167247772217 <class 'float'>


In [22]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[0.5219, 0.0000, 0.9139, 0.1432],
        [0.3364, 0.0000, 0.7071, 0.9078],
        [0.0754, 0.0000, 0.3594, 0.2153],
        [0.1818, 0.0000, 0.6951, 0.8460]])

tensor([[5.5219, 5.0000, 5.9139, 5.1432],
        [5.3364, 5.0000, 5.7071, 5.9078],
        [5.0754, 5.0000, 5.3594, 5.2153],
        [5.1818, 5.0000, 5.6951, 5.8460]])


In [23]:
t = torch.ones(5)
print(f"t : {t}")
n =t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [24]:
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


In [25]:
n = np.ones(5)
t = torch.from_numpy(n)

In [26]:
print(f"n : {n}")
np.add(n, 1, out = n)
print(f"t : {t}")
print(f"n : {n}")

n : [1. 1. 1. 1. 1.]
t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
