In [3]:
import torch
x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [4]:
print(f"Gradient functioni for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient functioni for z = <AddBackward0 object at 0x7fd12df883d0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fd12df895d0>


In [5]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0015, 0.0793, 0.1631],
        [0.0015, 0.0793, 0.1631],
        [0.0015, 0.0793, 0.1631],
        [0.0015, 0.0793, 0.1631],
        [0.0015, 0.0793, 0.1631]])
tensor([0.0015, 0.0793, 0.1631])


In [9]:
z = torch.matmul(x, w) + b
print(z)
print(z.requires_grad)
with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z)
print(z.requires_grad)

tensor([-5.3834, -1.1642, -0.0429], grad_fn=<AddBackward0>)
True
tensor([-5.3834, -1.1642, -0.0429])
False


In [10]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [11]:
inp = torch.eye(5, requires_grad=True)
out = (inp +1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradient\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradient
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
